### ISSUE TITLE
Redesign login screens

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/Edlightened-Web#2]
Code is down, but the opening screens could look a lot better. 

//stuff that I found interesting: http://thecodeplayer.com/walkthrough/make-gauge-charts-using-canvas-and-javascript?s=rl

**Comment by AJDev77** [comment]
@javathunderman Do you have a design idea in mind? If not, I could try and see what I can do.

**Comment by javathunderman** [comment]
@AJDev77 We could have that first screen be exactly the thing I linked, and afterwards, it would be a login screen that looks akin to this: http://getbootstrap.com/examples/signin/, but with a darker color scheme.

**Comment by javathunderman** [comment]
@AJDev77 Anything on this? If you're too busy with MySurf (or our new name, hehe), I can handle this.

**Comment by AJDev77** [comment]
@javathunderman  I think I got the page working, but I did not get that first loading screen. It does not login, so that will need to be fixed. I will create a pull request so you look at it before it is put into <code>master</code>.

**Comment by javathunderman** [comment]
No PR required- commit at will.

**Comment by AJDev77** [comment]
@javathunderman I know, but I wanted to get feedback first.

**Comment by javathunderman** [comment]
Can be closed...
