### ISSUE TITLE
Github Linguist incorrectly identifies our code

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/Edlightened-Web#9]
@AJDev77 Since the latest commit, Github Linguist has been classifying 99% of our code as PHP. This, I'm pretty sure, isn't the case. It might be because of the Temboo files I put on here (Temboo has a lot of php files in their sdk), but I wanted to ping you before I go to the Linguist repo and file an issue there.

Github's Linguist language identifier: http://github.com/github/linguist

**Comment by javathunderman** [comment]
@AJDev77 Ping

**Comment by javathunderman** [comment]
Combing through our code, it seems like JS is the default language. I might go and ping someone from Github about this...

**Comment by AJDev77** [comment]
@javathunderman Sorry for the late reply... Yeah, looking through our code, we mostly have JS files, then PHP comes after that. GitHub might label it as PHP because they are assuming that the main files that we will be using are PHP, and JS is just in the background with the PHP files using the JS files.

**Comment by javathunderman** [comment]
Dunno why, but this has half fixed itself. It's still identifying PHP as the default language, and not JS, but the percentage of PHP files has gone down drastically. Looking into this. @AJDev77 Will ping someone at Github if this doesn't get fixed by the end of the week.

**Comment by javathunderman** [comment]
Pinged Github...

**Comment by javathunderman** [comment]
github/linguist#2385

**Comment by javathunderman** [comment]
Refer to above issue for explanation.
